version: 2

jobs:
  build:
    macos:
      xcode: "9.0.0"
    environment:
      CIRCLE_TEST_RESULTS: $HOME/test-results
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout

      - restore_cache:
          key: v1-gems-{{ checksum "Gemfile" }}
      - run:
          name: Setup Build
          command: |
            mkdir -p $CIRCLE_TEST_RESULTS
            echo "2.3" > .ruby-version
            gem update --system
            brew install shellcheck
            bundle check || bundle install --jobs=4 --retry=3 --path .bundle
      - save_cache:
          key: v1-gems-{{ checksum "Gemfile" }}
          paths:
            - .bundle

      - run:
          name: Check PR Metadata
          command: bundle exec danger || echo "danger failed"

      - run: bundle exec fastlane test

      - store_test_results:
          path: /Users/distiller/test-results

      - run:
          name: Post Test Results to GitHub
          command: bundle exec danger || echo "danger failed"
          when: always # Run this even when tests fail
